DevExtreme_AspNet_Data_Project/net/Sample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Sample.Controllers {
    public class HomeController : Controller {

        [Route("")]
        public IActionResult Index() {
            return View();
        }

        [Route("SearchApi")]
        public IActionResult SearchApi() {
            return View();
        }

        [Route("GroupedList")]
        public IActionResult GroupedList() {
            return View();
        }

    }
}

DevExtreme_AspNet_Data_Project/net/Sample/Controllers/NorthwindController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Sample.Models;
using DevExtreme.AspNet.Data;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;

namespace Sample.Controllers {

    [Route("nwind")]
    public class NorthwindController : Controller {
        NorthwindContext _nwind;

        public NorthwindController(NorthwindContext nwind) {
            _nwind = nwind;
        }

        [HttpGet("orders")]
        public object Orders(DataSourceLoadOptions loadOptions) {
            return DataSourceLoader.Load(_nwind.Orders, loadOptions);
        }

        [HttpGet("order-details")]
        public object OrderDetails(int orderID, DataSourceLoadOptions options) {
            return DataSourceLoader.Load(
                from i in _nwind.Order_Details
                where i.OrderID == orderID
                select new {
                    Product = i.Product.ProductName,
                    Price = i.UnitPrice,
                    Quantity = i.Quantity,
                    Sum = i.UnitPrice * i.Quantity
                },
                options
            );
        }

        [HttpGet("customers-lookup")]
        public object CustomersLookup(DataSourceLoadOptions options) {
            return DataSourceLoader.Load(
                from c in _nwind.Customers orderby c.CompanyName select new {
                    Value = c.CustomerID,
                    Text = $"{c.CompanyName} ({c.Country})"
                },
                options
            );
        }

        [HttpGet("shippers-lookup")]
        public object ShippersLookup(DataSourceLoadOptions options) {
            return DataSourceLoader.Load(
                from s in _nwind.Shippers orderby s.CompanyName select new {
                    Value = s.ShipperID,
                    Text = s.CompanyName
                },
                options
            );
        }

        [HttpPut("update-order")]
        public IActionResult UpdateOrder(int key, string values) {
            var order = _nwind.Orders.First(o => o.OrderID == key);
            JsonConvert.PopulateObject(values, order);

            if(!TryValidateModel(order))
                return BadRequest(ModelState.ToFullErrorString());

            _nwind.SaveChanges();

            return Ok();
        }

        [HttpPost("insert-order")]
        public IActionResult InsertOrder(string values) {
            var order = new Order();
            JsonConvert.PopulateObject(values, order);

            if(!TryValidateModel(order))
                return BadRequest(ModelState.ToFullErrorString());

            _nwind.Orders.Add(order);
            _nwind.SaveChanges();

            return Ok();
        }

        [HttpDelete("delete-order")]
        public void DeleteOrder(int key) {
            var order = _nwind.Orders.First(o => o.OrderID == key);
            _nwind.Orders.Remove(order);
            _nwind.SaveChanges();
        }

        [HttpGet("products")]
        public object Products(DataSourceLoadOptions loadOptions) {
            return DataSourceLoader.Load(
                _nwind.Products.Include(p => p.Category),
                loadOptions
            );
        }

    }
}

DevExtreme_AspNet_Data_Project/net/Sample/Views/Home/GroupedList.cshtml
@{
    Layout = "~/Views/_Layout.cshtml";
}

<div id="list"></div>
<script>
    $(function() {
        $("#list").dxList({
            dataSource: {
                store: DevExpress.data.AspNet.createStore({
                    loadUrl: "@Url.Action("Products", "Northwind")"
                }),
                group: "category.categoryName",
                sort: "productName",
                paginate: true,
                pageSize: 1 // group
            },
            grouped: true,
            itemTemplate: function(product) {
                return product.productName;
            }
        });
    });
</script>

DevExtreme_AspNet_Data_Project/net/Sample/Views/Home/Index.cshtml
@{
    Layout = "~/Views/_Layout.cshtml";
}
<div id="grid"></div>
<script>
    $(function() {
        $("#grid").dxDataGrid({

            dataSource: DevExpress.data.AspNet.createStore({
                key: "orderID",
                loadUrl: "@Url.Action("Orders", "Northwind")",
                updateUrl: "@Url.Action("UpdateOrder", "Northwind")",
                insertUrl: "@Url.Action("InsertOrder", "Northwind")",
                deleteUrl: "@Url.Action("DeleteOrder", "Northwind")",

                onBeforeSend: function(operation, ajaxSettings) {
                    // operation - any of "load", "update", "insert", "delete"
                    // ajaxSettings - http://api.jquery.com/jquery.ajax/
                }
            }),

            columns: [
                {
                    dataField: "customerID",
                    caption: "Customer",
                    lookup: {
                        valueExpr: "value",
                        displayExpr: "text",
                        dataSource: DevExpress.data.AspNet.createStore({
                            key: "value",
                            loadUrl: "@Url.Action("CustomersLookup", "Northwind")"
                        })
                    }
                },
                {
                    dataField: "orderDate",
                    dataType: "date",
                    headerFilter: {
                        groupInterval: "quarter"
                    }
                },
                {
                    dataField: "freight",
                    headerFilter: {
                        groupInterval: 100
                    }
                },
                "shipCountry",
                "shipRegion",
                {
                    dataField: "shipVia",
                    lookup: {
                        valueExpr: "value",
                        displayExpr: "text",
                        dataSource: DevExpress.data.AspNet.createStore({
                            key: "value",
                            loadUrl: "@Url.Action("ShippersLookup", "Northwind")"
                        })
                    }
                }
            ],

            groupPanel: { visible: true },
            filterRow: { visible: true },
            headerFilter: { visible: true },
            editing: {
                allowUpdating: true,
                allowAdding: true,
                allowDeleting: true
            },
            remoteOperations: true,
            grouping: {
                autoExpandAll: false
            },
            summary: {
                totalItems: [
                    { column: "freight", summaryType: "sum" }
                ],
                groupItems: [
                    { column: "freight", summaryType: "sum" },
                    { summaryType: "count" }
                ]
            },

            masterDetail: {
                enabled: true,
                template: function(container, options) {
                    $("<div>")
                        .dxDataGrid({
                            dataSource: DevExpress.data.AspNet.createStore({
                                loadUrl: "@Url.Action("OrderDetails", "Northwind")",
                                loadParams: { orderID: options.data.orderID }
                            })
                        })
                        .appendTo(container);
                }
            }
        });
    });
</script>

DevExtreme_AspNet_Data_Project/net/Sample/Views/Home/SearchApi.cshtml
@{
    Layout = "~/Views/_Layout.cshtml";
}

<div id="lookup"></div>
<script>
    $(function() {
        $("#lookup").dxLookup({
            dataSource: DevExpress.data.AspNet.createStore({
                loadUrl: "@Url.Action("Products", "Northwind")"
            }),
            valueExpr: "productID",
            displayExpr: "productName",
            searchEnabled: true
        });
    });
</script>