DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/ViewModels/EditorsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace WidgetGallery.ViewModels {
    public class EditorsViewModel {

        public string Name { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Extension { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public int Age { get; set; }
        public string Drink { get; set; }
        public string City { get; set; }
        public IEnumerable<string> Colors { get; set; }
        public IEnumerable<string> SelectedColors { get; set; }
        public string Color { get; set; }
        public DateTime Date { get; set; }
        public bool Accepted { get; set; }
    }
}

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/ViewModels/GalleryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace WidgetGallery.ViewModels {
    public class GalleryViewModel {
        public IEnumerable<string> Images { get; set; }
    }
}

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/ViewModels/ValidationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace WidgetGallery.ViewModels {
    public class ValidationViewModel {
        public string Name { get; set; }
        public DateTime BirthDate { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public int ZipCode { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public bool Agreement { get; set; }
    }
}

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Controllers/FileUploaderController.cs
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;

namespace WidgetGallery.Controllers {

    [Route("api/[controller]/[action]")]
    public class FileUploaderController : Controller {
        IHostingEnvironment _hostingEnvironment;

        public FileUploaderController(IHostingEnvironment hostingEnvironment) {
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpPost]
        public ActionResult Upload() {
            // Learn more on the functionality of the dxFileUploader widget at:
            // http://js.devexpress.com/Documentation/Guide/UI_Widgets/UI_Widgets_-_Deep_Dive/dxFileUploader/

            var myFile = Request.Form.Files["myFile"];
            var targetLocation = Path.Combine(_hostingEnvironment.WebRootPath, "uploads");

            try {
                var path = Path.Combine(targetLocation, myFile.FileName);

                // Uncomment to save the file
                //using(var fileStream = System.IO.File.Create(path)) {
                //    myFile.CopyTo(fileStream);
                //}
            } catch {
                Response.StatusCode = 400;
            }

            return new EmptyResult();
        }
    }

}

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WidgetGallery.Models.Northwind;
using WidgetGallery.ViewModels;
using Microsoft.Extensions.DependencyInjection;

namespace WidgetGallery.Controllers {

    public class HomeController : Controller {

        public ActionResult Index() {
            return RedirectToAction("DataGrid");
        }

        public ActionResult Editors() {
            return View(new EditorsViewModel {
                Colors = new[] { "red", "orange", "yellow", "green", "blue", "indigo", "violet" },
                SelectedColors = new[] { "red", "orange", "yellow" },
                Color = "#ff8800",
                Date = DateTime.Now,
                Age = 50,
                Accepted = true,
                Drink = "Coffee",
                City = "New York",
                Extension = "5467",
                Phone = "+1(202)555-01-92",
                Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ornare, magna ut lobortis eleifend, tellus est fringilla neque."
            });
        }

        public ActionResult Overlays() {
            return View();
        }

        public ActionResult List() {
            return View();
        }

        public ActionResult Gallery() {
            var images = new List<string>();
            foreach(var i in Enumerable.Range(1, 10))
                images.Add(Url.Content(String.Format("~/images/{0:D2}.png", i)));

            return View(new GalleryViewModel {
                Images = images
            });
        }

        public ActionResult DataGrid() {
            return View();
        }

        public ActionResult PivotGrid() {
            return View();
        }

        public ActionResult DataGridOData() {
            return View();
        }

        public ActionResult Form() {
            var nwind = HttpContext.RequestServices.GetService<NorthwindContext>();

            return View(new FormViewModel {
                FormData = nwind.Employees.First()
            });
        }

        public ActionResult Charts() {
            return View();
        }

        public ActionResult Navigation() {
            return View();
        }

        public ActionResult Scheduler() {
            return View();
        }

        public ActionResult GeoMap() {
            return View();
        }

        public ActionResult Gauges() {
            return View();
        }

        public ActionResult RangeSelector() {
            return View();
        }

        public ActionResult SparklinesBullets() {
            return View();
        }

        public ActionResult VectorMap() {
            return View();
        }

        public ActionResult TreeMap() {
            return View();
        }

        public ActionResult Validation() {
            return View(new ValidationViewModel());
        }

        public ActionResult FileUploader() {
            return View();
        }

    }
}

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/Charts.cshtml
<div class="row">
    <div class="col-md-6">
        @Html.Partial("Charts/_Chart")
    </div>
    <div class="col-md-6">
        @Html.Partial("Charts/_PieChart")
    </div>
</div>

<div class="row p-t-6">
    <div class="col-md-6">
        @Html.Partial("Charts/_StockChart")
    </div>
    <div class="col-md-6">
        @Html.Partial("Charts/_PolarChart")
    </div>
</div>

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/DataGridOData.cshtml
@(Html.DevExtreme().DataGrid()
    .DataSource(d => d.OData()
        .Version(4)
        .Url("http://services.odata.org/V4/Northwind/Northwind.svc/Products")
        .JSONP(true)
        .Key("ProductID")
        .Expand("Category")
    )
    .Columns(columns => {
        columns.Add().DataField("ProductName");
        columns.Add().DataField("Category.CategoryName").Caption("Category");
        columns.Add().DataField("UnitPrice").Format(f => f.Type(Format.Currency).Precision(2));
        columns.Add().DataField("Discontinued");
    })
    .Paging(p => p.PageSize(10))
    .FilterRow(f => f.Visible(true))
    .Selection(s => s
        .Mode(SelectionMode.Multiple)
        .ShowCheckBoxesMode(GridSelectionShowCheckBoxesMode.Always)
        .AllowSelectAll(false)
    )
)

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/Editors.cshtml
@model WidgetGallery.ViewModels.EditorsViewModel

<form>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>TextBox</label>
                @(Html.DevExtreme().TextBox()
                    .MaxLength(20)
                    .Placeholder("Max length 20")
                    .Value(Model.Name)
                )
            </div>

            <div class="form-group">
                <label>Password</label>
                @(Html.DevExtreme().TextBox()
                    .Mode(TextBoxMode.Password)
                    .Placeholder("Enter password")
                    .Value(Model.Password)
                )
            </div>

            <div class="form-group">
                <label>Masked value</label>
                @(Html.DevExtreme().TextBox()
                    .Mode(TextBoxMode.Tel)
                    .Placeholder("Enter phone")
                    .Mask("+0 (000) 000-00-00")
                    .UseMaskedValue(true)
                    .Value(Model.Phone)
                )
            </div>

            <div class="form-group">
                <label>TextBox read-only</label>
                @(Html.DevExtreme().TextBox()
                    .Mode(TextBoxMode.Text)
                    .ReadOnly(true)
                    .Value(Model.Extension)
                )
            </div>

            <div class="form-group">
                <label>TextArea</label>
                @(Html.DevExtreme().TextArea()
                    .Value("Some text")
                    .Spellcheck(true)
                    .Value(Model.Description)
                )
            </div>

            <div class="form-group">
                <label>NumberBox</label>
                <div>
                    @(Html.DevExtreme().NumberBox()
                        .Max(100)
                        .Min(0)
                        .Mode(NumberBoxMode.Number)
                        .Placeholder("Enter a number...")
                        .ReadOnly(false)
                        .ShowClearButton(true)
                        .ShowSpinButtons(true)
                        .Step(1)
                        .Value(Model.Age)
                    )
                </div>
            </div>

            <div class="form-group">
                <label>RadioGroup</label>
                <div class="row">
                    <div class="col-md-4">
                        @(Html.DevExtreme().RadioGroup()
                            .Items(items => {
                                items.Add().Text("Tea");
                                items.Add().Text("Coffee");
                                items.Add().Text("Juice");
                            })
                        )
                    </div>
                    <div class="col-md-8">
                        @(Html.DevExtreme().RadioGroup()
                            .Items(items => {
                                items.Add().Text("Tea");
                                items.Add().Text("Coffee");
                                items.Add().Text("Juice");
                            })
                            .ValueExpr("text")
                            .Value(Model.Drink)
                            .Layout(Orientation.Horizontal)
                        )
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label>Autocomplete</label>
                <div>
                    @(Html.DevExtreme().Autocomplete()
                        .DisplayValue("")
                        .MaxItemCount(6)
                        .MinSearchLength(2)
                        .Placeholder("Type country name")
                        .SearchMode(DropDownSearchMode.StartsWith)
                        .SearchTimeout(200)
                        .ShowClearButton(true)
                        .DataSource(d => d.WebApi().Controller("GeoNames").LoadAction("Countries"))
                        .Value(Model.Country)
                    )
                </div>
            </div>

            <div class="form-group">
                <label>Lookup</label>
                <div>
                    @(Html.DevExtreme().Lookup()
                        .Placeholder("Select the city")
                        .ApplyButtonText("Select")
                        .ApplyValueMode(EditorValueApplyMode.UseButtons)
                        .DataSource(d => d.WebApi().Controller("GeoNames").LoadAction("Cities").Key("this"))
                        .CloseOnOutsideClick(true)
                        .FieldTemplate(@<text><i><%= obj %></i></text>)
                        .PageLoadMode(ListPageLoadMode.NextButton)
                        .SearchMode(DropDownSearchMode.StartsWith)
                        .SearchPlaceholder("Enter the first letters")
                        .Shading(true)
                        .MinSearchLength(2)
                        .ShowDataBeforeSearch(true)
                        .ShowPopupTitle(false)
                        .Value(Model.City)
                    )
                </div>
            </div>

            <div class="form-group">
                <label>SelectBox</label>
                <div>
                    @(Html.DevExtreme().SelectBox()
                        .Placeholder("Select the color")
                        .DataSource(Model.Colors)
                        .AcceptCustomValue(true)
                    )
                </div>
            </div>

            <div class="form-group">
                <label>TagBox</label>
                <div>
                    @(Html.DevExtreme().TagBox()
                        .Placeholder("Select the color")
                        .DataSource(Model.Colors)
                        .AcceptCustomValue(true)
                        .Value(Model.SelectedColors)
                    )
                </div>
            </div>

            <div class="form-group">
                <div>
                    @(Html.DevExtreme().Button()
                        .Text("Submit")
                        .Icon("check")
                        .Type(ButtonType.Success)
                    )
                </div>
            </div>
        </div>

        <div class="col-md-6">

            <div class="form-group">
                <label>ColorBox</label>
                @(Html.DevExtreme().ColorBox()
                    .ApplyButtonText("Set Color")
                    .ApplyValueMode(EditorValueApplyMode.UseButtons)
                    .EditAlphaChannel(true)
                    .Placeholder("Edit color")
                    .Value(Model.Color)
                )
            </div>

            <div class="form-group">
                <label>DateBox date and time</label>
                @(Html.DevExtreme().DateBox()
                    .ApplyValueMode(EditorValueApplyMode.UseButtons)
                    .DisplayFormat(Format.ShortDateShortTime)
                    .Type(DateBoxFormat.Datetime)
                    .Interval(10)
                    .PickerType(DateBoxPickerType.Calendar)
                    .Value(Model.Date)
                )
            </div>

            <div class="form-group">
                <label>DateBox date</label>
                @(Html.DevExtreme().DateBox()
                    .ApplyValueMode(EditorValueApplyMode.Instantly)
                    .Type(DateBoxFormat.Date)
                    .PickerType(DateBoxPickerType.List)
                    .Value(Model.Date)
                )
            </div>

            <div class="form-group">
                <label>Calendar</label>
                @(Html.DevExtreme().Calendar()
                    .FirstDayOfWeek(FirstDayOfWeek.Monday)
                    .ZoomLevel(CalendarZoomLevel.Year)
                    .ShowTodayButton(true)
                    .Value(Model.Date)
                )
            </div>

            <div class="form-group">
                <label>Slider</label>
                @(Html.DevExtreme().Slider()
                    .KeyStep(1)
                    .Label(l => l
                        .Visible(true)
                        .Position(VerticalEdge.Bottom)
                    )
                    .Tooltip(t => t
                        .ShowMode(SliderTooltipShowMode.Always)
                        .Enabled(true)
                    )
                    .Value(Model.Age)
                    .Min(0)
                    .Max(100)
                )
            </div>

            <div class="form-group">
                <label>RangeSlider</label>
                @(Html.DevExtreme().RangeSlider()
                    .KeyStep(0.01)
                    .Step(0.01)
                    .Label(l => l
                        .Visible(true)
                        .Position(VerticalEdge.Bottom)
                    )
                    .Tooltip(t => t
                        .ShowMode(SliderTooltipShowMode.OnHover)
                        .Enabled(true)
                    )
                    .Start(-1.5)
                    .End(7.5)
                    .Visible(true)
                    .Min(-10)
                    .Max(10)
                )
            </div>

            <div class="form-group">
                <label>Switch</label>
                <div>
                    @(Html.DevExtreme().Switch()
                        .Value(Model.Accepted)
                        .OnText("I")
                        .OffText("O")
                    )

                    @(Html.DevExtreme().Switch()
                        .Value(!Model.Accepted)
                    )
                </div>

            </div>

            <div class="form-group">
                <label>CheckBox</label>
                <div>
                    @(Html.DevExtreme().CheckBox()
                        .Value(Model.Accepted)
                        .Text("Checked")
                    )

                    @(Html.DevExtreme().CheckBox()
                        .Value(JS.Undefined)
                        .Text("Indeterminate")
                    )

                    @(Html.DevExtreme().CheckBox()
                        .Value(!Model.Accepted)
                        .Text("Unchecked")
                    )
                </div>
            </div>

        </div>
    </div>

</form>

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/FileUploader.cshtml
<div class="row">
    <div class="col-md-12">
        @(Html.DevExtreme().FileUploader()
            .SelectButtonText("Add images")
            .LabelText("Drop images here")
            .Name("myFile")
            .UploadMode(FileUploadMode.UseButtons)
            .Accept("image/*")
            .UploadUrl(Url.Action("Upload", "FileUploader"))
            .Multiple(true)
        )
    </div>
</div>

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/Form.cshtml
@model WidgetGallery.ViewModels.FormViewModel

@(Html.DevExtreme().Form()
    .ColCount(2)
    .FormData(Model.FormData)
    .Items(rootItems => {

        rootItems.AddGroup()
            .Caption("General Info")
            .Items(generalGroup => {
                generalGroup.AddSimple()
                    .DataField("EmployeeID")
                    .HelpText("This field is generated automatically")
                    .Editor(e => e
                        .TextBox()
                        .ReadOnly(true)
                    );

                generalGroup.AddSimple()
                    .DataField("FirstName")
                    .IsRequired(true)
                    .Editor(e => e.TextBox());

                generalGroup.AddSimple()
                    .DataField("LastName")
                    .IsRequired(true)
                    .Editor(e => e.TextBox());

                generalGroup.AddSimple()
                    .DataField("HireDate")
                    .Editor(e => e.DateBox());

                generalGroup.AddSimple()
                    .DataField("Title")
                    .Editor(e => e.TextBox());

                generalGroup.AddSimple()
                    .DataField("TitleOfCourtesy")
                    .Editor(e => e
                        .SelectBox()
                        .DataSource(new[] { "Mr.", "Ms.", "Mrs.", "Dr." })
                    );
            });

        rootItems.AddGroup()
            .Caption("Personal Info")
            .Items(personalGroup => {

                personalGroup.AddSimple()
                    .DataField("BirthDate")
                    .Editor(e => e.DateBox());

                personalGroup.AddTabbed()
                    .Tabs(tabs => {

                        tabs.Add()
                            .Title("Address")
                            .Items(addressItems => {

                                addressItems.AddSimple()
                                    .Label(l => l.Location(FormLabelLocation.Left))
                                    .DataField("Address");

                                addressItems.AddSimple()
                                    .Label(l => l.Location(FormLabelLocation.Left))
                                    .DataField("City");

                                addressItems.AddSimple()
                                    .Label(l => l
                                        .Text("State")
                                        .Location(FormLabelLocation.Left)
                                    )
                                    .DataField("Region");

                                addressItems.AddSimple()
                                    .Label(l => l.Location(FormLabelLocation.Left))
                                    .DataField("PostalCode");

                                addressItems.AddSimple()
                                    .Label(l => l.Location(FormLabelLocation.Left))
                                    .DataField("Country");

                            });

                        tabs.Add()
                            .Title("Phone")
                            .Items(phoneItems => {

                                phoneItems.AddSimple()
                                    .Label(l => l.Location(FormLabelLocation.Left))
                                    .DataField("HomePhone");

                                phoneItems.AddSimple()
                                    .Label(l => l.Location(FormLabelLocation.Left))
                                    .DataField("Extension");

                            });

                        tabs.Add()
                            .Title("Notes")
                            .Items(notesItems => {

                                notesItems.AddSimple()
                                    .DataField("Notes")
                                    .Editor(e => e.TextArea().Height(100));

                            });

                    });
            });

    })
    .LabelLocation(FormLabelLocation.Top)
    .MinColWidth(100)
)

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/Gauges.cshtml
<div class="row">
    <div class="col-md-6">
       @Html.Partial("Gauges/_DeviationsBarGauge")
    </div>
    <div class="col-md-6">
        @Html.Partial("Gauges/_SpeedBarGauge")
    </div>
</div>

<div class="row p-t-6">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-4">
                @Html.Partial("Gauges/_TemperatureLinearGauge")
            </div>
            <div class="col-md-4">
                @Html.Partial("Gauges/_HumidityLinearGauge")
            </div>
            <div class="col-md-4">
                @Html.Partial("Gauges/_PressureLinearGauge")
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                @Html.Partial("Gauges/_SubvaluesLinearGauge")
            </div>
            <div class="col-md-12">
                @Html.Partial("Gauges/_RangesLinearGauge")
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                @Html.Partial("Gauges/_SubvaluesCircularGauge")
            </div>
            <div class="col-md-6">
                @Html.Partial("Gauges/_RangesCircularGauge")
            </div>
        </div>
    </div>
</div>

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/GeoMap.cshtml
<div class="row">
    <div class="col-md-12">
        @(Html.DevExtreme().Map()
            .Key(k => k.Google("AIzaSyDk2m6n8ICK7FSmTHBLlapAWF3epiDdkHE"))
            .ID("map")
            .Provider(GeoMapProvider.Google)
            .Height(400)
            .Width("100%")
            .Zoom(14)
            .Controls(true)
            .Center(40.753889, -73.981389)
            .Markers(markers => {
                markers.Add().Coordinates(40.753889, -73.981389);
            })
            .Routes(routes => {
                routes.Add().Locations(locations => {
                    locations.Add().Coordinates(40.753889, -73.981389);
                    locations.Add().Coordinates(40.753889, -73.95);
                });
            })
        )
    </div>
</div>
<div class="row p-t-6">
    <div class="col-md-12">
        @(Html.DevExtreme().SelectBox()
            .Items(items => {
                items.Add().Text("Google").Option("value", "google");
                items.Add().Text("Bing").Option("value", "bing");
            })
            .ValueExpr("value")
            .DisplayExpr("text")
            .Value("google")
            .OnValueChanged("selectBox_valueChanged")
        )
    </div>
</div>

<script>
    function selectBox_valueChanged(e) {
        $("#map").dxMap("instance").option("provider", e.value);
    }
</script>

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/Navigation.cshtml
<div class="row" style="background: rgba(96,96,96,.1)">
    <div class="col-md-12">
        @Html.Partial("Navigation/_Menu")
    </div>
</div>

<div class="row p-t-6">
    <div class="col-md-3">
        @Html.Partial("Navigation/_TreeView")
    </div>
    <div class="col-md-6">
        <div class="row" style="padding: 10px 0;">
            <div class="col-md-12">
                @Html.Partial("Navigation/_Toolbar")
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.Partial("Navigation/_TabPanel")
            </div>
        </div>
    </div>

    <div class="col-md-3">
        @Html.Partial("Navigation/_Accordion")
    </div>
</div>

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/PivotGrid.cshtml
@(Html.DevExtreme().PivotGrid()
        .Height(500)
        .AllowExpandAll(true)
        .AllowSorting(true)
        .AllowSortingBySummary(true)
        .AllowFiltering(true)
        .DataSource(d => d
            .Fields(fields => {
                fields.Add().DataField("CategoryName")
                    .Area(PivotGridArea.Row)
                    .Width(120);

                fields.Add().DataField("ProductName")
                    .Area(PivotGridArea.Row)
                    .Width(150);

                fields.Add().DataField("OrderDate")
                    .Area(PivotGridArea.Column)
                    .DataType(PivotGridDataType.Date);

                fields.Add().DataField("Sum")
                    .Caption("Total")
                    .DataType(PivotGridDataType.Number)
                    .SummaryType(SummaryType.Sum)
                    .Format(Format.Currency)
                    .Area(PivotGridArea.Data);
            })
            .Store(s => s.WebApi().Controller("PivotGridData"))
        )
        .FieldChooser(f => f.Layout(PivotGridFieldChooserLayout.Layout0))
        .Scrolling(s => s.Mode(PivotGridScrollingMode.Virtual))
        .FieldPanel(p => p.Visible(true).ShowFilterFields(false))
)

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/RangeSelector.cshtml
<div class="row">
    <div class="col-md-12">
        @(Html.DevExtreme().RangeSelector()
            .Title("Ships By Month")
            .DataSource(d => d.WebApi()
                .Controller("ChartsData")
                .LoadAction("ShipsByMonth")
                .LoadParams(new { shipper = "Federal Shipping" })
            )
            .Size(s => s.Height(400))
            .Chart(c => c
                .CommonSeriesSettings(s => s
                    .Type(SeriesType.StepArea)
                    .ArgumentField("Month")
                )
                .Series(series => {

                    series.Add()
                        .ValueField("TotalAmount")
                        .Color("yellow");

                    series.Add()
                        .ValueField("Amount");

                })
            )
            .Scale(s => s
                .ValueType(ChartDataType.DateTime)
                .TickInterval(i => i.Months(1))
                .MinorTickInterval(i => i.Months(1))
            )
            .SliderMarker(m => m.Format(Format.MonthAndYear))
        )
    </div>
</div>
<div class="row p-t-6">
    <div class="col-md-12">
        @(Html.DevExtreme().RangeSelector()
            .Title("Copper Production in 2013")
            .DataSource("~/SampleData/Copper.json")
            .Chart(c => c
                .CommonSeriesSettings(s => s
                    .ArgumentField("country")
                    .Type(SeriesType.Bar)
                )
                .Series(series => {
                    series.Add()
                        .Name("Copper")
                        .ValueField("copper");
                })

            )
            .Scale(s => s.UseTicksAutoArrangement(false))
        )
    </div>
</div>
<div class="row p-t-6">
    <div class="col-md-12">
        @(Html.DevExtreme().RangeSelector()
            .Title("Vacation Period")
            .Scale(s => s
                .StartValue(new DateTime(2016, 3, 1))
                .EndValue(new DateTime(2016, 9, 1))
                .MinorTickInterval(VizTimeInterval.Day)
                .TickInterval(i => i.Days(7))
                .MinRange(VizTimeInterval.Week)
                .MaxRange(r => r.Months(4))
                .MinorTick(t => t.Visible(false))
            )
            .SliderMarker(m => m.Format(Format.MonthAndDay))
            .SelectedRange(r => r
                .StartValue(new DateTime(2016, 6, 30))
                .EndValue(new DateTime(2016, 7, 14))
            )
            .Margin(m => m.Top(20))
            .Size(s => s.Height(175))
        )
    </div>
</div>

DevExtreme.AspNet.Mvc-NETCore/WidgetGallery/Views/Home/Scheduler.cshtml
@(Html.DevExtreme().Scheduler()
        .DataSource(d => d.WebApi()
            .Controller("SchedulerData")
            .LoadAction("Appointments")
            .Key("OrderID")
        )
        .StartDateExpr("OrderDate")
        .EndDateExpr("ShippedDate")
        .TextExpr("CustomerName")
        .RemoteFiltering(true)
        .Groups(new [] { "ShipVia" })
        .Resources(res => {
            res.Add()
                .FieldExpr("ShipVia")
                .Label("Shipper")
                .AllowMultiple(false)
                .DataSource(x => x.WebApi()
                    .Controller("SchedulerData")
                    .LoadAction("Resources")
                );
        })
        .RecurrenceRuleExpr("")
        .CurrentDate(new DateTime(1997, 7, 4))
        .Views(new SchedulerView[] {
            SchedulerView.Month,
            SchedulerView.Agenda
        })
        .CurrentView(SchedulerView.Month)
        .Editing(e => e.AllowAdding(false).AllowDeleting(false))
        .OnAppointmentFormCreated("scheduler_appointmentFormCreated")
        .Height(600)
)

<script>

    function scheduler_appointmentFormCreated(e) {
        var form = e.form;

        form.itemOption("CustomerName", { label: { text: "Customer" }, editorOptions: { readOnly: true } });
        form.itemOption("OrderDate", { label: { text: "Order Date" } });
        form.itemOption("ShippedDate", { label: { text: "Shipped Date" } });

        form.itemOption("allDay", { visible: false });
        form.itemOption("description", { visible: false });
    }

</script>